Shop2Hand/Areas/Admin/Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shop2Hand.Extension;
using Shop2Hand.Helpper;
using Shop2Hand.Models;
using Shop2Hand.ModelViews;

namespace Shop2Hand.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminAccountController : Controller
    {
        private readonly Shop2HandContext _context;
        public INotyfService _notyfService { get; }
        public AdminAccountController(Shop2HandContext context, INotyfService notyfService)
        {
            _notyfService = notyfService;
            _context = context;
        }

        // GET: Admin/AdminAccount
        public async Task<IActionResult> Index()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            List<SelectListItem> IsTrangThai = new List<SelectListItem>();
            IsTrangThai.Add(new SelectListItem() { Text = "Active", Value = "1" });
            IsTrangThai.Add(new SelectListItem() { Text = "Block", Value = "0" });
            ViewData["IsTrangThai"] = IsTrangThai;
            var Shop2HandContext = _context.Accounts.Include(a => a.Role);
            return View(await Shop2HandContext.ToListAsync());
        }

        // GET: Admin/AdminAccount/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.Role)
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Admin/AdminAccount/Create
        public IActionResult Create()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View();
        }

        // POST: Admin/AdminAccount/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,Phone,Email,Password,Salt,Active,FullName,LastLogin,CreateDate,RoleId")] Account account)
        {
            if (ModelState.IsValid)
            {
                string salt = Utilities.GetRandomKey();
                account.Salt = salt;
                account.Password = (account.Phone + salt.Trim()).ToMD5();
                account.CreateDate = DateTime.Now;

                // Tạo ngẫu nhiên mật khẩu
                _context.Add(account);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới thành công!");
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }

        //Channge PAssword
        public IActionResult ChangePassword()
        {
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangePassword(ChangePassword model)
        {
            if (ModelState.IsValid)
            {
                var taikhoan = _context.Accounts.AsNoTracking().SingleOrDefault(x => x.Email == model.Email);
                if (taikhoan == null) return RedirectToAction("Login", "Accounts");
                var pass = (model.PasswordNow.Trim() + taikhoan.Salt.Trim()).ToMD5();
                {
                    string passnew = (model.Password.Trim() + taikhoan.Salt.Trim()).ToMD5();
                    taikhoan.Password = passnew;
                    taikhoan.LastLogin = DateTime.Now;
                    _context.Update(taikhoan);
                    _context.SaveChanges();
                    _notyfService.Success("Đổi mật khẩu thành công");
                    return RedirectToAction("Login", "Accounts", new { Area = "Admin" });
                }
            }


            return View();
        }

        // GET: Admin/AdminAccount/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }

        // POST: Admin/AdminAccount/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AccountId,Phone,Email,Password,Salt,Active,FullName,LastLogin,CreateDate,RoleId")] Account account)
        {
            if (id != account.AccountId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.AccountId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuyenTruyCap"] = new SelectList(_context.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }

        // GET: Admin/AdminAccount/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.Role)
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Admin/AdminAccount/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Accounts == null)
            {
                return Problem("Entity set 'Shop2HandContext.Accounts'  is null.");
            }
            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                _context.Accounts.Remove(account);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccountExists(int id)
        {
            return _context.Accounts.Any(e => e.AccountId == id);
        }
    }
}

Shop2Hand/Areas/Admin/Views/AdminAccount/Create.cshtml
@model Shop2Hand.Models.Account

@{
    ViewData["Title"] = "Thêm tài khoản quản trị";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card-body">
    <h4>Tạo mới tài khoản quản trị</h4>
    <div class="mt-10" style="max-width: 700px">
        <form asp-controller="AdminAccount" asp-action="Create" method="post">
            <div class="row mt-3">
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputEmail4">Họ và tên</label class="mb-2">
                    <input type="text" class="form-control" asp-for="FullName" placeholder="Họ và tên">
                </div>
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputPassword4">Số điện thoại</label class="mb-2">
                    <input type="text" class="form-control" asp-for="Phone" placeholder="Số điện thoại">
                </div>
            </div>
            <div class="row mt-3">
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputEmail4">Email</label class="mb-2">
                    <input type="text" class="form-control" asp-for="Email" placeholder="Email">
                </div>
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputEmail4">Mật khẩu</label class="mb-2">
                    <input type="password" class="form-control" asp-for="Password" placeholder="Mật khẩu">
                </div>
            </div>
            <div class="row my-3">
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputPassword4">Quyền truy cập</label class="mb-2">
                    <select class="form-control" asp-for="RoleId" asp-items="@ViewBag.QuyenTruyCap" required>
                        <option value="0" disabled selected>Chọn quyền truy cập</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <input asp-for="Active" type="checkbox">
                    <label class="mb-2" for="Active">Active</label class="mb-2">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Tạo mới</button>
        </form>
    </div>

</div>

Shop2Hand/Areas/Admin/Views/AdminAccount/Delete.cshtml
@model Shop2Hand.Models.Account

@{
    ViewData["Title"] = "Xóa tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastLogin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastLogin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.RoleId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AccountId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Shop2Hand/Areas/Admin/Views/AdminAccount/Details.cshtml
@model Shop2Hand.Models.Account

@{
    ViewData["Title"] = "Chi tiết tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastLogin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastLogin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.RoleId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AccountId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Shop2Hand/Areas/Admin/Views/AdminAccount/Edit.cshtml
@model Shop2Hand.Models.Account

@{
    ViewData["Title"] = "Thêm tài khoản quản trị";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card-body">
    <h4>Chỉnh sửa thông tin</h4>
    <div class="mt-10" style="max-width: 700px">
        <form asp-controller="AdminAccount" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AccountId" />
            <div class="row mt-3">
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputEmail4">Họ và tên</label class="mb-2">
                    <input type="text" class="form-control" asp-for="FullName" placeholder="Họ và tên">
                </div>
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputPassword4">Số điện thoại</label class="mb-2">
                    <input type="text" class="form-control" asp-for="Phone" placeholder="Số điện thoại">
                </div>
            </div>
            <div class="row mt-3">
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputEmail4">Email</label class="mb-2">
                    <input type="text" class="form-control" asp-for="Email" placeholder="Email">
                </div>
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputEmail4">Mật khẩu</label class="mb-2">
                    <input type="password" class="form-control" asp-for="Password" placeholder="Mật khẩu">
                </div>
            </div>
            <div class="row my-3">
                <div class="form-group col-md-6">
                    <label class="mb-2" for="inputPassword4">Quyền truy cập</label class="mb-2">
                    <select class="form-control" asp-for="RoleId" asp-items="@ViewBag.QuyenTruyCap" required>
                        <option value="0" disabled selected>Chọn quyền truy cập</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <input asp-for="Active" type="checkbox">
                    <label class="mb-2" for="Active">Active</label class="mb-2">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Lưu thay đổi</button>
        </form>
    </div>

</div>

Shop2Hand/Areas/Admin/Views/AdminAccount/Index.cshtml
@model IEnumerable<Shop2Hand.Models.Account>

@{
    ViewData["Title"] = "Danh sách tài khoản quản trị";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="main-content">
    <div class="pagetitle">

        <nav>
            <ol class="breadcrumb">
                <a asp-controller="Home" asp-area="Admin" asp-action="Index" class="breadcrumb-item">Trang chủ</a>
                <a asp-controller="AdminAccount" asp-area="Admin" asp-action="Index" class="breadcrumb-item">Danh sách quyền truy cập</a>
                <a asp-controller="Home" asp-area="Admin" asp-action="Index" class="breadcrumb-item active">Thông tin quyền truy cập</a>
            </ol>
        </nav>
       
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row mt-4">
                <div class="col-lg-8">
                    <div class="d-md-flex">
                        <div class="mb-3 me-3">
                            <select  asp-items="ViewBag.QuyenTruyCap" class="custom-select" style="min-width: 180px;">
                                <option value="" disabled selected>Chọn quyền truy cập</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <select class="custom-select" style="min-width: 180px;" id="idstatus" asp-items="ViewBag.IsTrangthai">
                                <option selected value="" disabled>Chọn trạng thái</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 text-end mb-3">
                    <a class="btn btn-primary" asp-controller="AdminAccount" asp-action="Create">
                        <i class="fa-solid fa-plus"></i>
                        <span>Thêm tài khoản</span>
                    </a>
                </div>
            </div>
            <div class="table-responsive">
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <div class="row align-items-center mb-5"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="DataTables_Table_0_length"><label>Show <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="custom-select "><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="DataTables_Table_0_filter" class="dataTables_filter float-end"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="DataTables_Table_0"></label></div></div></div><div class="row">
                        <div class="col-sm-12">
                            <table class="table table-hover e-commerce-table dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting"  >ID</th>
                                        <th class="sorting" >Họ tên</th>
                                        <th class="sorting"  >Email</th>
                                        <th class="sorting"  >Số điện thoại</th>
                                        <th class="sorting"  >Quyền truy cập</th>
                                        <th class="sorting"  >Trạng thái</th>
                                        <th class="sorting"  ></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="">
                                                    @item.AccountId
                                                </td>
                                                <td>
                                                    <div class="d-flex align-items-center">
                                                        <img class="img-fluid rounded" src="assets/images/others/thumb-9.jpg" style="max-width: 60px" alt="">
                                                        <h6 class="mb-0 ms-2">@item.FullName</h6>
                                                    </div>
                                                </td>
                                                <td>@item.Email</td>
                                                <td>@item.Phone</td>
                                                <td>@item.Role.RoleName</td>
                                                <td>
                                                    @if (item.Active)
                                                    {

                                                    <div class="d-flex align-items-center">
                                                        <div class="badge badge-success badge-dot me-2"></div>
                                                        <div>Active</div>
                                                    </div>
                                                    }
                                                    else
                                                    {

                                                        <div class="d-flex align-items-center">
                                                            <div class="badge badge-success badge-dot me-2"></div>
                                                            <div>Block</div>
                                                        </div>
                                                    }
                                                </td>
                                                <td class="text-end">
                                                    <a  asp-action="Details" asp-route-id="@item.AccountId" class="btn btn-success">Chi tiết</a>
                                                    <a  asp-action="Edit" asp-route-id="@item.AccountId" class="btn btn-warning">Chỉnh sửa</a>
                                                    <a   asp-action="Delete" asp-route-id="@item.AccountId" class="btn btn-danger">Xóa</a>
                                                </td>
                                            </tr>

                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>