Shop2Hand/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Shop2Hand.Helpper;
using Shop2Hand.Models;

namespace Shop2Hand.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly Shop2HandContext _context;
        public INotyfService _notyfService { get; }
        public AdminProductsController(Shop2HandContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }


        // GET: Admin/AdminProducts
        public IActionResult Index(int? page, int CateId = 0)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;

            List<Product> lsProducts = new List<Product>();
            if (CateId != 0)
            {
                lsProducts = _context.Products
                .AsNoTracking()
                .Where(x => x.CateId == CateId)
                .Include(x => x.Cate)
                .OrderBy(x => x.ProductId).ToList();
            }
            else
            {
                lsProducts = _context.Products
                .AsNoTracking()
                .Include(x => x.Cate)
                .OrderBy(x => x.ProductId).ToList();
            }



            PagedList<Product> models = new PagedList<Product>(lsProducts.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentCateID = CateId;

            ViewBag.CurrentPage = pageNumber;

            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName");

            return View(models);
        }
        public IActionResult Filtter(int CateId = 0)
        {
            var url = $"/Admin/AdminProducts?CateId={CateId}";
            if (CateId == 0)
            {
                url = $"/Admin/AdminProducts";
            }
            return Json(new { status = "success", redirectUrl = url });
        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cate)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Description,CateId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                product.ProductName = Utilities.ToTitleCase(product.ProductName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(product.ProductName) + extension;
                    product.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                }
                if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "default.jpg";
                product.Alias = Utilities.SEOUrl(product.ProductName);
                product.DateModified = DateTime.Now;
                product.DateCreated = DateTime.Now;

                _context.Add(product);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            var Shop2HandContext = _context.Products
                .AsNoTracking()
                .Include(p => p.Cate)
                .OrderByDescending(p => p.ProductId);
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName", product.CateId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName", product.CateId);
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Description,CateId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ProductName = Utilities.ToTitleCase(product.ProductName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(product.ProductName) + extension;
                        product.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(product.Thumb)) product.Thumb = "default.jpg";
                    product.Alias = Utilities.SEOUrl(product.ProductName);
                    product.DateModified = DateTime.Now;

                    _context.Update(product);
                    _notyfService.Success("Cập nhật thành công");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CateId", "CateName", product.CateId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cate)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Shop2Hand/Areas/Admin/Views/AdminProducts/Create.cshtml
@model Shop2Hand.Models.Product

@{
    ViewData["Title"] = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex mt-3 align-items-center justify-content-between">
            <div class="mt-3">
                <button class="btn btn-primary mb-3">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>

        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <button class="nav-link active fw-semibold" id="product-edit-basic-tab" data-bs-toggle="tab" data-bs-target="#product-edit-basic" type="button" role="tab" aria-controls="product-edit-basic" aria-selected="true">Thông tin cơ bản</button>
                <button class="nav-link fw-semibold" id="product-edit-option-tab" data-bs-toggle="tab" data-bs-target="#product-edit-option" type="button" role="tab" aria-controls="product-edit-option" aria-selected="false">Thông tin thiết lập</button>
                <button class="nav-link fw-semibold" id="product-edit-description-tab" data-bs-toggle="tab" data-bs-target="#product-edit-description" type="button" role="tab" aria-controls="product-edit-description" aria-selected="false">Mô tả</button>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="product-edit-basic" role="tabpanel" aria-labelledby="product-edit-basic-tab" tabindex="0">
                <div class="card">
                    <div class="card-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label class="fw-semibold" for="productName">Tên sản phẩm</label>
                            <input type="text" class="form-control" asp-for="ProductName">
                        </div>
                        <div class="form-group mt-2">
                            <label class="fw-semibold" for="productName">Mô tả ngắn</label>
                            <input type="text" class="form-control" asp-for="ShortDesc">
                        </div>
                        <div class="row mt-3">
                            <div class="form-group col-md-6">
                                <label class="fw-semibold" for="productPrice">Giá bán</label>
                                <input type="text" class="form-control" asp-for="Price">
                            </div>
                            <div class="form-group col-md-6">
                                <label class="fw-semibold" for="productPrice">Giá giảm</label>
                                <input type="text" class="form-control" asp-for="Discount">
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="form-group col-6 ">
                                <label  asp-for="CateId" class="fw-semibold" for="productCategory">Danh mục sản phẩm</label>
                                <br />
                                @*<select class="custom-select mt-3" asp-for="CateId" id="CateId" name="CateId" style="min-width: 200px;" asp-items="ViewBag.DanhMuc">
                                    <option value="" selected disabled>Chọn Danh mục</option>
                                </select>*@
                                <select asp-for="CateId" class="form-control" asp-items="ViewBag.DanhMuc"></select>
                            </div>
                            <div class="form-group col-6">
                                <label class="fw-semibold" for="productName" >Hàng tồn kho</label>
                                <input type="text" class="form-control" asp-for="UnitsInstock">
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <label class="fw-semibold" for="productBrand">Ảnh đại diện</label>
                            <br />
                            <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                            <span asp-validation-for="Thumb" class="text-danger"></span>
                        </div>
                        <div class="row mt-3">
                            <div class="mt-4">
                                <!---->
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="Active" asp-for="Active" checked>
                                    <label class="form-check-label" for="Active">Public </label>
                                </div>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="HomeFlag" asp-for="HomeFlag">
                                    <label class="form-check-label" for="HomeFlag">HomeFlag</label>
                                </div>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="BestSeller" asp-for="BestSeller">
                                    <label class="form-check-label" for="BestSeller">BestSeller</label>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="tab-pane fade" id="product-edit-option" role="tabpanel" aria-labelledby="product-edit-option-tab" tabindex="0">
                <div class="card">
                    <div class="card-body mt-3">
                        <div class="form-group">
                            <label class="fw-semibold" for="productSize">Title</label>
                            <input type="text" class="form-control" asp-for="Title">
                        </div>
                        <div class="form-group">
                            <label class="fw-semibold" for="productColors">MetaDesc</label>
                            <input type="text" class="form-control" asp-for="MetaDesc">
                        </div>
                        <div class="form-group">
                            <label class="fw-semibold" for="productFit">MetaKey</label>
                            <input type="text" class="form-control" asp-for="MetaKey">
                        </div>
                        <div class="form-group">
                            <label class="fw-semibold" for="productFit">Tags</label>
                            <input type="text" class="form-control" asp-for="Tags">
                        </div>
                    </div>
                </div>

            </div>
            <div class="tab-pane fade" id="product-edit-description" role="tabpanel" aria-labelledby="product-edit-description-tab" tabindex="0">
                <div class="card">
                    <div class="card-body mt-3 ">
                        <textarea class="summernote w-100" asp-for="Description"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>

    jQuery(document).ready(function () {
        $('.summernote').summernote({
            fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
            styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
            height: 700,
            minHeight: null,
            maxHeight: null,
            focus: true
        });
    });
</script>

Shop2Hand/Areas/Admin/Views/AdminProducts/Delete.cshtml
@model Shop2Hand.Models.Product

@{
    ViewData["Title"] = "Xóa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="pagetitle">
    <nav>
        <ol class="breadcrumb">
            <a asp-controller="Home" asp-area="Admin" asp-action="Index" class="breadcrumb-item">Home</a>
            <a asp-controller="Home" asp-area="AdminRoles" asp-action="Index" class="breadcrumb-item">Danh sách sản phẩm</a>
            <a asp-controller="Home" asp-area="Admin" asp-action="Index" class="breadcrumb-item active">Thông tin sản phẩm</a>
        </ol>
    </nav>
</div>
<h5 class="card-title">Thông tin sản phẩm : @Model.ProductName</h5>
<table class="table table-striped">
    <tbody>
        <tr>
            <td>ID:</td>
            <td>@Model.ProductId</td>
        </tr>
        <tr>
            <td>Tên sản phẩm:</td>
            <td>@Model.ProductName</td>
        </tr>
        <tr>
            <td>Mô tả ngắn:</td>
            <td>@Model.ShortDesc</td>
        </tr>
        <tr>
            <td>Mô tả:</td>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <td>ID Danh mục:</td>
            <td>@Model.CateId</td>
        </tr>
        <tr>
            <td>Danh mục:</td>
            <td>@Model.Cate.CateName</td>
        </tr>
        <tr>
            <td>Giá giảm:</td>
            <td>@Model.Discount</td>
        </tr>
        <tr>
            <td>Mô tả:</td>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <td>Ngày tạo:</td>
            <td>@Model.DateCreated</td>
        </tr>
        <tr>
            <td>Ngày chỉnh sửa:</td>
            <td>@Model.DateModified</td>
        </tr>
        <tr>
            <td>Tiêu đề:</td>
            <td>@Model.Title</td>
        </tr>
        <tr>
            <td>MetaDesc:</td>
            <td>@Model.MetaDesc</td>
        </tr>
        <tr>
            <td>MetaKey:</td>
            <td>@Model.MetaKey</td>
        </tr>
        <tr>
            <td>Tags:</td>
            <td>@Model.Tags</td>
        </tr>
        <tr>
            <td>Ảnh đại diện:</td>
            <td>
                <img src="/assets/images/@Model.Thumb" alt="@Model.Title" width="200" height="200" />
            </td>
        </tr>
        <tr>
            <td>Xác nhận xóa: </td>
            <td>
                <form asp-action="Delete" asp-controller="AdminProducts" asp-route-id="@Model.ProductId">
                    <input type="hidden" asp-for="ProductId" />
                    <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> |
                </form>
            </td>
        </tr>
    </tbody>
</table>

Shop2Hand/Areas/Admin/Views/AdminProducts/Details.cshtml
@model Shop2Hand.Models.Product

@{ ViewData["Title"] = "Thông tin sản phẩm" + Model.ProductName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home me-2"></i>Trang chủ</a>
            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Index" class="breadcrumb-item">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm : @Model.ProductName</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab mt-4">
    <div class="d-md-flex mb-4 align-items-center justify-content-between">
        <div class="media d-flex align-items-center mb-4">
            <div class="avatar avatar-image rounded">
                <img src="~/images/products/@Model.Thumb" height="70" width="70" alt="@Model.Title" />
            </div>
            <div class="ms-3">
                <h4 class="mb-0">@Model.ProductName</h4>
                <p class="text-muted mb-0">ID: #@Model.ProductId</p>
            </div>
        </div>
        <div class="mb-3">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminProducts" asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a>
        </div>
    </div>

</div>



<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active fw-bold" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">THÔNG TIN</button>
        <button class="nav-link fw-bold" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">ẢNH</button>
    </div>
</nav>
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
        <div class="container-fluid px-0">
            <div class="tab-content mt-3">
                <div class="tab-pane fade show active" id="product-overview">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">THÔNG TIN PAGE : @Model.ProductName</h4>

                            <table class="table table-responsive">
                                <tbody>
                                    <tr>
                                        <td>ID:</td>
                                        <td class="text-dark fw-semibold">@Model.ProductId</td>
                                    </tr>
                                    <tr>
                                        <td>Tên sản phẩm:</td>
                                        <td>@Model.ProductName</td>
                                    </tr>
                                    <tr>
                                        <td>Mô tả ngắn:</td>
                                        <td>@Model.ShortDesc</td>
                                    </tr>
                                    <tr>
                                        <td>Giá:</td>
                                        <td>@Model.Price.Value.ToString("#,##0") VNĐ</td>

                                    </tr>
                                    <tr>
                                        <td>Discount:</td>
                                        <td>@Model.Discount.Value.ToString("#,##0") VNĐ</td>
                                    </tr>
                                    <tr>
                                        <td>Trạng thái:</td>
                                        <td>
                                            @if (Model.Active)
                                            {
                                                <div class="switch me-3">
                                                    <input type="checkbox" id="switch-1" checked="" disabled />
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="switch me-3">
                                                    <input type="checkbox" id="switch-1" disabled />
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Bestseller:</td>
                                        <td>
                                            @if (Model.BestSeller)
                                            {
                                                <div class="switch me-3">
                                                    <input type="checkbox" id="switch-1" checked="" disabled />
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="switch me-3">
                                                    <input type="checkbox" id="switch-1" disabled />
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>HomeFlag:</td>
                                        <td>
                                            @if (Model.HomeFlag)
                                            {
                                                <div class="switch me-3">
                                                    <input type="checkbox" id="switch-1" checked="" disabled />
                                                    <label for="switch-1"></label>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="switch me-3">
                                                    <input type="checkbox" id="switch-1" disabled />
                                                    <label for="switch-1"></label>
                                                </div>
                                            }

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Danh mục:</td>
                                        <td>@Model.Cate.CateName</td>
                                    </tr>
                                    <tr>
                                        <td>Ngày tạo:</td>
                                        <td>@Model.DateCreated</td>
                                    </tr>
                                    <tr>
                                        <td>Ngày tạo:</td>
                                        <td>@Model.DateModified</td>
                                    </tr>
                                    <tr>
                                        <td>Tiêu đề:</td>
                                        <td>@Model.Title</td>
                                    </tr>
                                    <tr>
                                        <td>MetaDesc:</td>
                                        <td>@Model.MetaDesc</td>
                                    </tr>
                                    <tr>
                                        <td>MetaKey:</td>
                                        <td>@Model.MetaKey</td>
                                    </tr>
                                    <tr>
                                        <td>Tags:</td>
                                        <td>@Model.Tags</td>
                                    </tr>
                                    <tr>
                                        <td>Ảnh đại diện:</td>
                                        <td>
                                            <img width="200" height="200" src="~/images/products/@Model.Thumb" alt="@Model.Title" />
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title py-0">THÔNG TIN MÔ TẢ</h4>
                        </div>
                        <div class="card-body pt-4">
                            @Html.Raw(Model.Description)
                        </div>
                    </div>
                </div>

            </div>
        </div>



    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
        <div class="mt-3">
            <img class="img-fluid w-50" src="~/images/products/@Model.Thumb" alt="@Model.Title" />
        </div>
    </div>
</div>